# Generated by Django 5.1.5 on 2025-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default='parentemail@example.gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default='0000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
