# Generated by Django 5.1.5 on 2025-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default='default qualification', max_length=100),
            preserve_default=False,
        ),
    ]
