# Generated by Django 5.1.5 on 2025-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default='default location', max_length=100),
            preserve_default=False,
        ),
    ]
